package main

// This file will be generated by the import-generator
// It contains import statements and registration calls for all mounted policies
// DO NOT EDIT MANUALLY

func init() {
	// Policy registrations will be generated here
}
